<?php /*if ($loggedin){
          echo "Welcome " . $loginfirst . "!";
          echo '<a href = "/tools/view/logout.php" title = "logout" > | Logout </a>';
      }elseif ($cookiefirst){
          echo "Welcome " . $cookiefirst . "!";
          echo '<a href = "/tools/view/logout.php" title = "logout" > | Logout </a>';
      }else{
          echo '<a href = "/tools/view/login.php" title = "Login to coryfugate.com" > | Login </a>';
          echo '<a href = "/tools/view/logout.php" title = "Logout" > | Logout </a>';
      } */?>

<h1><span>coryfugate.com</span><img src="images/cory-logo.png" alt="coryfugate.com" /></h1>