<nav>
<ul>
    <li><a href ="/index.php" id="homenav" title="Home | coryfugate.com">Home</a></li>
    <li><a href ="resume.php" id="resumenav" title="Resume | coryfugate.com">Resume</a></li>
    <li> <a href ="portfolio.php" id="portfolionav" title="Portfolio | coryfugate.com">Portfolio</a></li>
    <li> <a href ="contact.php" id="contactnav" title="Contact | coryfugate.com">Contact</a></li>
</ul>
</nav>

