
<a href ="/oldsite/pages/copyright.shtml" title="View Copyright Information">
&copy;2010 Cory Fugate, All Rights Reserved.</a>
<div id="footernav">
<dl>
    <dt><a href="/oldsite/pages/contact.php" title="Contact Me">
     Contact</a></dt>
    <dt> | <a href="/oldsite/pages/colophon.shtml" title="View the Colophon for coryfugate.com">
     Colophon</a></dt>
    <dt> | <a href="/oldsite/pages/modularizationplan.shtml" title="View the Modularization Plan for coryfugate.com">
     Modularization Plan</a></dt>
    <dt> | <a href="/oldsite/pages/siteplan.shtml" title="View the Site Plan for coryfugate.com">
     Site Plan</a></dt>
     <dt> | <a href="/oldsite/pages/styleguide.shtml" title="View the Style Guide for coryfugate.com">
     Style Guide</a> | </dt>
</dl>

    <a href="http://www.facebook.com/people/Cory-Fugate/100000152284103" title="Cory Fugate">
      <img src="/oldsite/images/facebook.png" alt="facebook" /></a>
</div>

<br /><em>*This site uses CSS 3.</em>