<dl>
    <dt><a href ="/oldsite/index.shtml" id="homenav" title="Homepage @ coryfugate.com">
        <span>
        <!--<img src="/images/homenav.png" alt="home" width="85" height="40" />-->
        Home
        </span>
        </a>
    </dt>
    <dt><a href ="/oldsite/pages/aboutme.shtml" id="aboutmenav" title="About Me @ coryfugate.com">
        <span>
        <!--<img src="/images/aboutmenav.png" alt="about me" width="110" height="40" />-->
        About Me
        </span>
        </a>
    </dt>
    <dt><a href ="/oldsite/pages/interests.shtml" id="interestsnav" title="Interests @ coryfugate.com">
        <span>
        <!--<img src="/images/interestsnav.png" alt="interests" width="105" height="40" />-->
        Interests
        </span>
        </a>
    </dt>
    <dt> <a href ="/oldsite/pages/resume.shtml" id="resumenav" title="Resume @ coryfugate.com">
        <span>
        <!--<img src="/images/resumenav.png" alt="resume" width="95" height="40" />-->
        Resume
        </span>
        </a>
    </dt>
    <dt> <a href ="/oldsite/pages/portfolio/portfolio.shtml" id="portfolionav" title="Portfolio @ coryfugate.com">
        <span>
        <!--<img src="/images/portfolionav.png" alt="portfolio" width="105" height="40" />-->
        Portfolio
        </span>
        </a>
    </dt>
    <dt> <a href ="/oldsite/pages/assignments/assignments.shtml" id="assignmentsnav" title="Assignments for CIT 230 class @ coryfugate.com">
        <span>
        <!--<img src="/images/assignmentsnav.png" alt="assignments" width="130" height="40" />-->
        Assignments
        </span>
        </a>
    </dt>
    <dt> <a href ="/oldsite/pages/contact.php" id="contactmenav" title="Contact Me">
       <span>
       <!--<img src="/images/contactmenav.png" alt="contactme" width="130" height="40" />-->
       Contact Me
       </span>
       </a>
    </dt>
</dl>
 
 
