
<h1><a href="/" title="Homepage :: Cory Fugate"><img src="images/logo.png" alt="Design and Development Patch"></a></h1>

<nav>
<ul>
    <li><a href ="bio.php" id="bionav" title="Bio | coryfugate.com">Bio</a></li>
    <li><a href ="resume.php" id="resumenav" title="Resume | coryfugate.com">Resume</a></li>
    <li id="portfolionav"><a href ="portfolio.php" title="Portfolio | coryfugate.com">Portfolio</a>
        <ul>
            <li><a href="photos.php" title ="Photography Portfolio | coryfugate.com">Photography</a></li>
            <li><a href="product.php" title ="Product Redesign | coryfugate.com">Product Redesign</a></li>
            <li><a href="logo.php" title ="Logo Design Portfolio | coryfugate.com">Logo Design</a></li>
            <li><a href="web.php" title ="Web Design Portfolio | coryfugate.com">Web Design</a></li>
            <li><a href="print.php" title ="Print Design Portfolio | coryfugate.com">Print Design</a></li>
            <li><a href="podcast.php" title ="Podcast | coryfugate.com">Podcast</a></li>
            <li><a href="selfport.php" title ="Self-portrait | coryfugate.com">Self-portrait</a></li>
        </ul>
    </li>
    <li> <a href ="contact.php" id="contactnav" title="Contact | coryfugate.com">Contact</a></li>
</ul>
</nav>