<nav>
	<ul>
		<li><a href = "index.php" title = "homepage">home</a></li>
		<li><a href = "howitworks.php" title = "how it works">how it works</a></li>
		<li><a href = "designs.php" title = "view our wedding, invite, and greeting stationery designs">designs</a></li>
		<li><a href = "shop.php" title = "purchase printable DIY stationery from our etsy shop">shop</a></li>
                <li><a href = "blog.php" title = "visit my blog">blog</a></li>
                <li><a href = "contact.php" title = "get in touch with me">contact</a></li>
        </ul>
</nav>
