
<p class="activitiesnavheading"><strong>&copy;Space Exploration Programs:</strong></p>

<dl>
            <dt>
                <a href="/classes/cit230/spacecamp/pages/activities/zerogravity.shtml" id="zerogravnav" title="Zero-Gravity @spacecamp.com">
                Zero-Gravity Training
                <!--<img src="/classes/cit230/spacecamp/images/zerogravnav.png" alt="Zero-Gravity" width="77" height="7" />--></a>
            </dt>
            <dt>
                <a href="/classes/cit230/spacecamp/pages/activities/gforce.shtml" id="gforcenav" title="G-Force Training @spacecamp.com">
                G-Force Training
                <!--<img src="/classes/cit230/spacecamp/images/gforcenav.png" alt="G-Force Training" width="100" height="7" />-->
                </a>
            </dt>
            <dt>
                 <a href="/classes/cit230/spacecamp/pages/activities/marswallclimb.shtml" id="marswallnav" title="Mars Wall Climb @spacecamp.com">
                 Mars Wall Climb
                 <!--<img src="/classes/cit230/spacecamp/images/marswallnav.png" alt="Mars Wall Climb" width="97" height="7" />-->
                 </a>
            </dt>
            <dt>
                 <a href="/classes/cit230/spacecamp/pages/activities/commandcenter.shtml" id="commandnav" title="Command Center @spacecamp.com">
                 Command Center Training
                 <!--<img src="/classes/cit230/spacecamp/images/commandnav.png" alt="Command Center Training" width="100" height="7"/>-->
                 </a>   
            </dt>
        </dl>