<dl>
    <dt><a href ="index.html" id="homenav" title="Homepage @ Space Camp">

            <img src="images/homenav.png" alt="Home" />
        </a>
    </dt>
    <dt><a href ="pages/activities/activities.html" id="activitiesnav" title="Activities @ Space Camp">
        <img src="images/activitiesnav.png" alt="Activities" />
        </a>
    </dt>
    <dt><a href ="pages/qualifications.html" id="qualificationsnav" title="How do you qualify? @ Space Camp">
        <img src="images/qualificationsnav.png" alt="Qualifications" />
        </a>
    </dt>
    <dt><a href ="pages/staff.html" id="staffnav" title="Staff @ Space Camp">
        <img src="images/staffnav.png" alt="Staff" />
        </a>
    </dt>
    <dt><a href ="pages/contact.php" id="contactnav" title="Contact us">
        <img src="images/contactnav.png" alt="Contact" />
        </a>
    </dt>
</dl>
 
 
