    
<form method="get" action="http://www.google.com/search">

<div style="width:300px;float:right; color:#FFFFFF;">
<table border="0" cellpadding="0">
<tr><td>
<input type="text"   name="q" size="25"
 maxlength="255" value="" /></td><td>
<input type="submit" value="Search the Web" /></td></tr>
</table>
</div>

</form>

    <h1><img src="/classes/cit230/spacecamp/images/spacecamplogo.png" width="753" height="37" alt="Space Camp" />
    </h1>
    

