<dl>
    <dt><a href ="/classes/cit230/spacecamp/index.shtml" id="homenav" title="Homepage @ Space Camp">

            <img src="/classes/cit230/spacecamp/images/homenav.png" alt="Home" />
        </a>
    </dt>
    <dt><a href ="/classes/cit230/spacecamp/pages/activities/activities.shtml" id="activitiesnav" title="Activities @ Space Camp">
        <img src="/classes/cit230/spacecamp/images/activitiesnav.png" alt="Activities" />
        </a>
    </dt>
    <dt><a href ="/classes/cit230/spacecamp/pages/qualifications.shtml" id="qualificationsnav" title="How do you qualify? @ Space Camp">
        <img src="/classes/cit230/spacecamp/images/qualificationsnav.png" alt="Qualifications" />
        </a>
    </dt>
    <dt><a href ="/classes/cit230/spacecamp/pages/staff.shtml" id="staffnav" title="Staff @ Space Camp">
        <img src="/classes/cit230/spacecamp/images/staffnav.png" alt="Staff" />
        </a>
    </dt>
    <dt><a href ="/classes/cit230/spacecamp/pages/contact.php" id="contactnav" title="Contact us">
        <img src="/classes/cit230/spacecamp/images/contactnav.png" alt="Contact" />
        </a>
    </dt>
</dl>
 
 
