

<a href="/classes/cit230/spacecamp/pages/copyright.shtml" title="View Copyright Information">
&copy;2010 Space Camp, All Rights Reserved.</a>
<div id="footernav">
<dl>
    <dt><a href="/classes/cit230/spacecamp/pages/contact.php" title="Contact">Contact</a></dt>
    <dt> | <a href="/classes/cit230/spacecamp/pages/colophon.shtml" title="View the Colophon for SpaceCamp.">Colophon</a></dt>
    <dt> | <a href="/classes/cit230/spacecamp/pages/siteplan.shtml" title="View the Site Plan for SpaceCamp">Site Plan</a></dt>
    <dt> | <a href="/classes/cit230/spacecamp/pages/resources.shtml" title="View the Resources used in SpaceCamp">Resources</a></dt>
</dl>
    <br />Last Update: 7 April 2010
</div>

<br /><br />Designed by Cory Fugate | <em>*This site uses CSS 3.</em>
