 <div id="nav">
            <ul>
                <li><a href="/classes/comm310/index.shtml" title="Home | COM310 Guide">| Home</a></li>
                <li><a href="/classes/comm310/overview.shtml" title="Overview | COM310 Guide">| Overview</a></li>
                <li><a href="/classes/comm310/htmlpgs/index.shtml" title="HTML | COM310 Guide">| HTML</a>
					<ul>
						<li><a href="/classes/comm310/htmlpgs/index.shtml" title="HTML | COM310 Guide">Intro</a></li>
               			 <li><a href="/classes/comm310/htmlpgs/htmlbasics.shtml" title ="HTML basics | CIT330 GUIDE">Basics</a></li>
               			 <li><a href="/classes/comm310/htmlpgs/text.shtml" title ="HTML Text | CIT330 GUIDE">Text</a></li>
              			 <li><a href="/classes/comm310/htmlpgs/links.shtml" title ="HTML Links | CIT330 GUIDE">Links</a></li>
            		</ul>
				</li>
                <li><a href="/classes/comm310/csspgs/index.shtml" title="CSS | COM310 Guide">| CSS</a>
					<ul>
						<li><a href="/classes/comm310/csspgs/index.shtml" title="CSS | COM310 Guide">Intro</a></li>
						<li><a href="/classes/comm310/csspgs/cssbasics.shtml" title ="CSS basics | CIT330 GUIDE">Basics</a></li>
						<li><a href="/classes/comm310/csspgs/text.shtml" title ="CSS Text | CIT330 GUIDE">Text</a></li>
						<li><a href="/classes/comm310/csspgs/links.shtml" title ="CSS Links | CIT330 GUIDE">Links</a></li>
					</ul>
				</li>
                <li><a href="/classes/comm310/phppgs/" title="PHP | COM310 Guide">| PHP</a>
					<ul>
						<li><a href="/classes/comm310/phppgs/" title="PHP | COM310 Guide">Intro</a></li>
						<li><a href="/classes/comm310/phppgs/phpprimer.shtml" title ="PHP primer | CIT330 GUIDE">Primer</a></li>
						
					</ul>
				</li>
                <li><a href="/classes/comm310/assignmentpgs/index.shtml" title="Assignments | COM310 Guide">| Assignments</a>
					<ul>
						<li><a href="/classes/comm310/csszen" title= "Css Zen assignment">Css Jurrasic Garden</a></li>
						<li><a href="/classes/comm310/bigjuds" title ="Big Jud's Redesign">Big Jud's Redesign</a></li>
					</ul>
				</li>
            </ul>

  </div>