
<a href ="/cory2010/pages/copyright.html" title="View Copyright Information">
&copy;2010 Cory Fugate, All Rights Reserved.</a>
<div id="footernav">
<dl>
    <dt><a href="/cory2010/pages/contact.html" title="Contact Me">
     Contact</a></dt>
    <dt> | <a href="/cory2010/pages/colophon.html" title="View the Colophon for coryfugate.com">
     Colophon</a></dt>
    <dt> | <a href="/cory2010/pages/modularizationplan.html" title="View the Modularization Plan for coryfugate.com">
     Modularization Plan</a></dt>
    <dt> | <a href="/cory2010/pages/siteplan.html" title="View the Site Plan for coryfugate.com">
     Site Plan</a></dt>
     <dt> | <a href="/cory2010/pages/styleguide.html" title="View the Style Guide for coryfugate.com">
     Style Guide</a> | </dt>
</dl>

    <a href="http://www.facebook.com/people/Cory-Fugate/100000152284103" title="Cory Fugate">
      <img src="/cory2010/images/facebook.png" alt="facebook" /></a>
</div>

<br /><em>*This site uses CSS 3.</em>